### ISSUE TITLE
Cannot  build in docker

### ISSUE THREAD

**Issue by juxeii** [nowsecure/r2frida#476] opened 2023-04-17 07:57 UTC
Trying to build r2frida in docker.
I have tried
`RUN r2pm -ci r2frida`
and
```
RUN git clone https://github.com/nowsecure/r2frida.git && \
    cd r2frida && \
    make -j40 && \
    make user-install
```
Both fail with a bunch of missing `*.js` files.
```
make[1]: Entering directory '/home/r2/r2frida'
cc -g src/r2frida-compile.c -fPIC -g -L/usr/local/lib -lr_core -lr_config -lr_debug -lr_bin -lr_anal -lr_bp -lr_egg -lr_asm -lr_lang -lr_flag -lr_search -lr_syscall -lr_fs -lr_magic -lr_arch -lr_esil -lr_reg -lr_io -lr_socket -lr_cons -lr_crypto -lr_util -ldl -Wl,--start-group -Iext/frida \
        -I/usr/local/include/libr -L/usr/local/lib -lr_util -ldl ext/frida/libfrida-core.a -lresolv \
        -pthread -Iext/frida -o src/r2frida-compile
/usr/bin/ld: missing --end-group; added as last command line option
make[1]: Leaving directory '/home/r2/r2frida'
make io_frida.so
make[1]: Entering directory '/home/r2/r2frida'
src/r2frida-compile -o src/_agent.js -Sc src/agent/index.ts
[
  {
    'category': <'error'>,
    'code': <int64: 2307>,
    'file': <{
      'path': <'/home/r2/r2frida/src/agent/index.ts'>,
      'line': <int64: 0>,
      'character': <int64: 19>
    }>,
    'text': <"Cannot find module './config.js' or its corresponding type declarations.">
  },
  {
    'category': <'error'>,
    'code': <int64: 2307>,
    'file': <{
      'path': <'/home/r2/r2frida/src/agent/index.ts'>,
      'line': <int64: 1>,
      'character': <int64: 22>
    }>,
    'text': <"Cannot find module './lib/anal.js' or its corresponding type declarations.">
  },
  {
    'category': <'error'>,
    'code': <int64: 2307>,
    'file': <{
      'path': <'/home/r2/r2frida/src/agent/index.ts'>,
      'line': <int64: 2>,
      'character': <int64: 25>
    }>,
    'text': <"Cannot find module './lib/java/android.js' or its corresponding type declarations.">
  },
  {
    'category': <'error'>,
    'code': <int64: 2307>,
    'file': <{
      'path': <'/home/r2/r2frida/src/agent/index.ts'>,
      'line': <int64: 3>,
      'character': <int64: 25>
    }>,
    'text': <"Cannot find module './lib/info/classes.js' or its corresponding type declarations.">
  },
  {
    'category': <'error'>,
    'code': <int64: 2307>,
    'file': <{
      'path': <'/home/r2/r2frida/src/agent/index.ts'>,
      'line': <int64: 4>,
      'character': <int64: 24>
    }>,
    'text': <"Cannot find module './lib/darwin/index.js' or its corresponding type declarations.">
  },

```
```
ERROR: compilation failed
make[1]: Leaving directory '/home/r2/r2frida'
make[1]: *** [Makefile:221: src/_agent.js] Error 1
make: *** [Makefile:159: all] Error 2
```
Any ideas what is wrong here?
Other r2 plugins works just fine, e.g.
```
RUN r2pm init && r2pm -U
RUN r2pm -ci r2dec
```

**Comment by trufae** [comment] 2023-04-17 08:25
This is a known bug in frida. You have 3 options here:

- Upgrade your docker to be ubuntu 2022 or alpine
- Use the precompiled agent (theres a config flag for that)
- Wait until the bug is fixed in frida

**Comment by trufae** [comment] 2023-04-18 08:23
@oleavr fixed this bug in Frida 16.0.14 :) just retry the build with latest r2frida from git and it should work (confirmed by the CI)

about the missing plugin, set the `R2_DEBUG=1` env var and you'll find out the reason why the plugin is not loaded. also if you are using r2frida in docker you'll need a privileged container

**Comment by juxeii** [comment] 2023-04-18 08:34
Thx. Here is the output.(`16.0.14` being used)

```
r2 frida:///bin/ls
DEBUG: Calling plugin init = 0
DEBUG: plugin DB beeing initted
DEBUG: RCore.cmd('ecoo')
DEBUG: RCore.cmd('ft alloc malloc free$ calloc kalloc realloc')
DEBUG: RCore.cmd('ft crypto encrypt decrypt aes AES blowfish _des _rc2 serpent _cbc')
DEBUG: RCore.cmd('ft dylib dlopen dlsym dlclose mmap LoadLibrary GetProcAddress')
DEBUG: RCore.cmd('ft env getenv putenv unsetenv setenv GetEnvironmentVariable SetEnvironmentVariable ExpandEnvironmentStrings')
DEBUG: RCore.cmd('ft fs open$ close read$ write CloseHandle FindFirstFileW _wfopen _wstat ftruncate lseek _chsize GetFullPathName realpath RemoveDirectory DeleteFile CreateFile WriteFile UnmapViewOfFile CreateFileMapping MapViewOfFile readlink chmod fchmod chown stat fstat lstat fstatat lstat64 stat64 chflags fchflags lchflags')
DEBUG: RCore.cmd('ft network socket connect bind$ listen accept sendto recvfrom gethostbyname htons ntohs')
DEBUG: RCore.cmd('ft process getpid getppid kill exit abort assert gethostid sethostid sysctl')
DEBUG: RCore.cmd('ft stdout ^printf puts write')
DEBUG: RCore.cmd('ft string strcat strcpy strncpy strlen strtok strstr strlcpy asprintf sprintf snprintf')
DEBUG: RCore.cmd('ft tags.py import os from sys import argv for fname in argv[1:]: with open(fname) as f: text = ' '.join(f.read().splitlines()) print('ft %s %s' % (os.path.basename(fname), text))')
DEBUG: RCore.cmd('ft threads pthread_create pthread_mutex_init pthread_cond_init CreateThread TerminateThread WaitForSingleObject GetCurrentThreadId')
DEBUG: RCore.cmd('ft time settimeofday gettimeofday time adjtime ctime timed date$ sleep Sleep usleep clock_nanosleep localtime asctime difftime gmtime mktime timelocal timegm tzfile tzset')
DEBUG: Loading /usr/local/lib/radare2/5.8.2/io_shm.so
DEBUG: Cannot find symbol 'radare_plugin' in library '/usr/local/lib/radare2/5.8.2/io_shm.so'
DEBUG: Cannot open directory '/home/reiss/.local/share//radare2/plugins'
DEBUG: Cannot open directory '/usr/local/lib/radare2-extras/5.8.2'
DEBUG: Cannot open directory '/usr/local/lib/radare2-bindings/5.8.2'
ERROR: Cannot open 'frida:///bin/ls'
DEBUG: Calling plugin fini = 1_

```
So, the symbol `radare_plugin` is missing. Any idea how to resolve this?

**Comment by trufae** [comment] 2023-05-18 12:42
Can you retry with latest code in git? I fixed several issues related to the build

**Comment by trufae** [comment] 2023-05-18 12:43
This was a bug in frida affecting ubuntu20. It should be fine now

**Closed by trufae** 2023-05-18 12:43 UTC

**Comment by juxeii** [comment] 2023-05-18 18:08
Thx. Now, when running

```
RUN pip install r2pipe && npm install --unsafe-perm -g r2pipe
RUN wget --no-check-certificate https://github.com/radareorg/radare2/releases/download/5.8.6/radare2_5.8.6_amd64.deb && \
    dpkg -i radare2_5.8.6_amd64.deb && \
    apt-get install -f && \
    useradd -m r2 && adduser r2 sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER r2
WORKDIR /home/r2
ENV HOME /home/r2
RUN r2pm init && r2pm -U && r2pm -ci r2dec && \
    git clone https://github.com/nowsecure/r2frida.git && \
    cd r2frida && ./configure --with-precompiled-agent && \
    make -j20 && make user-install && rm -rf /home/r2/r2frida
```
Radare2 installation seems to work now, but with the frida plugin installation is now a new problem:

```
 => ERROR [standalone-tools 7/9] RUN r2pm init && r2pm -U && r2pm -ci r2dec &&     git clone https://github.com/nowsecure/r2frida.git &&     cd r2frida && ./configure --with-precompiled-agent &&      22.7s
------
 > [standalone-tools 7/9] RUN r2pm init && r2pm -U && r2pm -ci r2dec &&     git clone https://github.com/nowsecure/r2frida.git &&     cd r2frida && ./configure --with-precompiled-agent &&     make -j20 && make user-install && rm -rf /home/r2/r2frida:
#19 0.478 WARN: Action words will be deprecated in r2-5.9.x, use -U instead of init
#19 0.580 INFO: Nothing to upgrade
#19 0.580 INFO: git clone --depth=10 --recursive https://github.com/radareorg/radare2-pm /home/r2/.local/share//radare2/r2pm/git/radare2-pm
#19 0.584 Cloning into '/home/r2/.local/share//radare2/r2pm/git/radare2-pm'...
#19 1.482 INFO: Nothing to upgrade
#19 1.487 hint: Pulling without specifying how to reconcile divergent branches is
#19 1.487 hint: discouraged. You can squelch this message by running one of the following
#19 1.487 hint: commands sometime before your next pull:
#19 1.487 hint:
#19 1.487 hint:   git config pull.rebase false  # merge (the default strategy)
#19 1.487 hint:   git config pull.rebase true   # rebase
#19 1.487 hint:   git config pull.ff only       # fast-forward only
#19 1.487 hint:
#19 1.487 hint: You can replace "git config" with "git config --global" to set a default
#19 1.487 hint: preference for all repositories. You can also pass --rebase, --no-rebase,
#19 1.487 hint: or --ff-only on the command line to override the configured default per
#19 1.487 hint: invocation.
#19 2.139 Already up to date.
#19 2.207 INFO: Cleaning r2dec
#19 2.253 INFO: Using r2-5.8.6 and r2pm-5.8.6
#19 2.253 INFO: Cleaning r2dec
#19 2.253 INFO: git clone --depth=10 --recursive https://github.com/wargio/r2dec-js /home/r2/.local/share/radare2/r2pm/git//r2dec
#19 2.257 Cloning into '/home/r2/.local/share/radare2/r2pm/git//r2dec'...
#19 3.240 INFO: Starting install for r2dec
#19 3.240 INFO: R2PM_NEEDS: Found python3 in PATH
#19 3.240 INFO: R2PM_NEEDS: Found gcc in PATH
#19 3.240 INFO: R2PM_NEEDS: Found make in PATH
#19 3.290 INFO: SCRIPT=<<EOF
#19 3.290 INFO:         export CFLAGS='-DR2DEC_HOME="${R2PM_GITDIR}/r2dec"'
#19 3.290       ${MAKE} -C p USE_JSC=1 V= || exit 1
#19 3.290       if [ "${GLOBAL}" = 1 ]; then
#19 3.290               ${MAKE} -C p uninstall
#19 3.290               ${MAKE} -C p install V= USE_JSC=1 || exit 1
#19 3.290       else
#19 3.290               ${MAKE} -C p user-uninstall
#19 3.290               ${MAKE} -C p user-install V= USE_JSC=1 || exit 1
#19 3.290       fi
#19 3.290 INFO: EOF
#19 3.295 make: Entering directory '/home/r2/.local/share/radare2/r2pm/git/r2dec/p'
#19 3.784 awk '{if(/@JSC_SOURCES@/)exit;print}' < r2dec_jsc.c.in > r2dec_jsc.c
#19 3.788 /usr/local/bin/python3 make_jsc.py .. >> r2dec_jsc.c
#19 4.501 awk 'BEGIN{A=0}{if(A==1){print}if(/@JSC_SOURCES@/)A=1}' < r2dec_jsc.c.in >> r2dec_jsc.c
#19 4.505 make build
#19 4.506 make[1]: Entering directory '/home/r2/.local/share/radare2/r2pm/git/r2dec/p'
#19 4.973 echo "[CC] duktape/duktape.o"
#19 4.975 [CC] duktape/duktape.o
#19 4.975 cc -DR2DEC_HOME="/home/r2/.local/share/radare2/r2pm/git/r2dec" -g -O3 -std=c99 -Wall -fPIC -I./duktape -DUSE_JSC=1 -g -O3 -std=c99 -Wall -fPIC -I./duktape -DUSE_JSC=1  -c duktape/duktape.c -o duktape/duktape.o
#19 21.47 echo "[CC] duktape/duk_console.o"
#19 21.47 [CC] duktape/duk_console.o
#19 21.47 cc -DR2DEC_HOME="/home/r2/.local/share/radare2/r2pm/git/r2dec" -g -O3 -std=c99 -Wall -fPIC -I./duktape -DUSE_JSC=1 -g -O3 -std=c99 -Wall -fPIC -I./duktape -DUSE_JSC=1  -c duktape/duk_console.c -o duktape/duk_console.o
#19 21.52 duktape/duk_console.c:19:10: fatal error: r_cons.h: No such file or directory
#19 21.52    19 | #include <r_cons.h>
#19 21.52       |          ^~~~~~~~~~
#19 21.52 compilation terminated.
#19 21.53 make[1]: *** [Makefile:59: duktape/duk_console.o] Error 1
#19 21.53 make[1]: Leaving directory '/home/r2/.local/share/radare2/r2pm/git/r2dec/p'
#19 21.53 make: *** [Makefile:39: all] Error 2
#19 21.53 make: Leaving directory '/home/r2/.local/share/radare2/r2pm/git/r2dec/p'
#19 21.53 Cloning into 'r2frida'...
#19 22.58 checking build system type... x86_64-unknown-linux-gnu
#19 22.58 checking host system type... x86_64-unknown-linux-gnu
#19 22.58 checking target system type... x86_64-unknown-linux-gnu
#19 22.58 checking for working directories... current
#19 22.58 using prefix '/usr/local'
#19 22.58 checking for pkg-config... /usr/bin/pkg-config
#19 22.58 checking for c compiler... gcc
#19 22.65 checking exec r2 -v... ok
#19 22.70 Using PKGCONFIG: /usr/bin/pkg-config
#19 22.70 checking pkg-config flags for r_core... no
#19 22.70 This package is required
------
executor failed running [/bin/sh -c r2pm init && r2pm -U && r2pm -ci r2dec &&     git clone https://github.com/nowsecure/r2frida.git &&     cd r2frida && ./configure --with-precompiled-agent &&     make -j20 && make user-install && rm -rf /home/r2/r2frida]: exit code: 1
```
When switching back to

```
RUN pip install r2pipe && npm install --unsafe-perm -g r2pipe
ARG R2_TAG=5.8.6
LABEL r2-docker latest
RUN DEBIAN_FRONTEND=noninteractive dpkg --add-architecture i386 && \
    git clone -q --depth 1 https://github.com/radare/radare2.git -b ${R2_TAG}  && \
    ./radare2/sys/install.sh && \
    useradd -m r2 && adduser r2 sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER r2
WORKDIR /home/r2
ENV HOME /home/r2
RUN r2pm init && r2pm -U && r2pm -ci r2dec && \
    git clone https://github.com/nowsecure/r2frida.git && \
    cd r2frida && ./configure --with-precompiled-agent && \
    make -j20 && make user-install && rm -rf /home/r2/r2frida
```
Both radare2 and frida will be installed. Any idea what went wrong?

**Comment by trufae** [comment] 2023-05-18 19:15
Pass /usr to the argument of sys/install. Because i guess your pkgconfig is not looking at /usr/local. Otherwise you can set the PKG_CONFIG_PATH envvar

**Comment by juxeii** [comment] 2023-05-18 21:12
I now have this, setting pkgconfig at the beginning:

```
ENV PKG_CONFIG_PATH /usr
RUN pip install r2pipe && npm install --unsafe-perm -g r2pipe
RUN wget --no-check-certificate https://github.com/radareorg/radare2/releases/download/5.8.6/radare2_5.8.6_amd64.deb && \
    dpkg -i radare2_5.8.6_amd64.deb && \
    apt-get install -f && \
    useradd -m r2 && adduser r2 sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER r2
WORKDIR /home/r2
ENV HOME /home/r2
RUN r2pm init && r2pm -U && r2pm -ci r2dec && \
    git clone https://github.com/nowsecure/r2frida.git && \
    cd r2frida && ./configure --with-precompiled-agent && \
    make -j20 && make user-install && rm -rf /home/r2/r2frida
```
Exact same error as before:
`#19 21.36 duktape/duk_console.c:19:10: fatal error: r_cons.h: No such file or directory`

**Comment by trufae** [comment] 2023-05-19 07:24
Thats not how pkgconfig works. The path must be /usr/local/lib/pkgconfig

**Comment by trufae** [comment] 2023-05-19 07:26
But this is a different problem because you are installing the deb files. Not compiling r2.

to be able to compile something you need to install the -dev package which contains the .h and .pc files

**Comment by trufae** [comment] 2023-05-19 07:26
Btw you can also install r2frisa using r2pm

**Comment by juxeii** [comment] 2023-05-19 08:03
Thank you very much for your help. I am using r2pm for frida now and it works.
Here is the working snippet in case others are facing similar issues.

```
ARG R2_TAG=5.8.6
RUN pip install r2pipe && npm install --unsafe-perm -g r2pipe
RUN wget --no-check-certificate https://github.com/radareorg/radare2/releases/download/${R2_TAG}/radare2_${R2_TAG}_amd64.deb && \
    dpkg -i radare2_${R2_TAG}_amd64.deb && \
    apt-get install -f && \
    useradd -m r2 && adduser r2 sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER r2
WORKDIR /home/r2
ENV HOME /home/r2
RUN r2pm init && r2pm -U && r2pm -ci r2dec && r2pm -ci r2frida
```
