### ISSUE TITLE
Compilation failed on windows 10x64

### ISSUE THREAD

**Issue by unabomber78** [nowsecure/r2frida#456] opened 2023-02-13 10:58 UTC
Compiling the Compiler...
r2frida-compile.c
[
  {
    'category': <'error'>,
    'code': <int64: 6053>,
    'text': <"File 'C:/Users/User/.local/share/radare2/r2pm/git/r2frida/src/agent/index.js' not found.\n  The file is in the program because:\n    Root file specified for compilation">
  }
]
ERROR: compilation failed
DONE
WARN: CreateFileMapping: (0x3ee) The volume for a file has been externally altered so that the opened file is no longer valid.

HEADER DONE
Compiling the Agent...
cl /O2 /MT /nologo /LD /Gy /D_USRDLL /D_WINDLL /DFRIDA_VERSION_STRING="16.0.9" io_frida.c /I"C:\progs\radare2\include" /I"C:\progs\radare2\include\libr" /I"C:\progs\radare2\include\libr\sdb" /I"C:\Users\User\.local\share\radare2\r2pm\git\r2frida\src" /I"C:\Users\User\.local\share\radare2\r2pm\git\r2frida\src\frida" "C:\Users\User\.local\share\radare2\r2pm\git\r2frida\src\frida\frida-core.lib" "C:\progs\radare2\lib\*.lib"
io_frida.c
io_frida.c(130): error C2059: syntax error: ','
io_frida.c(917): warning C4034: sizeof returns 0
Compilation Failed

**Comment by trufae** [comment] 2023-02-13 12:32
The Ci is silently failing 🤫 https://github.com/nowsecure/r2frida/actions/runs/4162373354/jobs/7201465777

So thanks for the headsup. ill take care of this

**Comment by trufae** [comment] 2023-05-18 14:29
dupe of dupe of https://github.com/nowsecure/r2frida/issues/444 (there are 5 issues about r2frida not working on windows) when thats a known issue and probably a bug in frida, i'm slowly investigating the issue but i didnt managed to find the reason why the compiled scripts are not parsed properly by frida inside r2frida.

**Closed by trufae** 2023-05-18 14:29 UTC
