### ISSUE TITLE
throw new SyntaxError("unexpected character") when trying to load script compiled with frida-compile -c

### ISSUE THREAD

**Issue by dogtopus** [nowsecure/r2frida#487] opened 2023-05-10 01:37 UTC
See title.

**Comment by trufae** [comment] 2023-05-10 07:42
Can you explain what did you do?

is this happening just after building r2frida?
Are you trying to run a frida compiled script withon r2frida?
Which version of frida-compile are you using?
Can you share the steps to reproduce?
Did you tried using r2frida-compile instead?

**Comment by dogtopus** [comment] 2023-05-10 15:43
> is this happening just after building r2frida?

I believe yes.

> Are you trying to run a frida compiled script withon r2frida?

Yes.

> Which version of frida-compile are you using?

16.1.9

> Can you share the steps to reproduce?

Mostly just run `frida-compile agent/index.ts -o _agent.js -c` via npm and load with `:. _agent.js` right away in r2frida.

I can try to reproduce this with a minimal example but that might take a bit of time.

> Did you tried using r2frida-compile instead?

No but I could try.

**Comment by trufae** [comment] 2023-05-10 21:35
If i understood the issue properly this happens to me only on windows. Works fine on linux and mac. Its a known issue after updating to frida16 and iirc until 16.1.18 i wasnt able to build the agent in ubuntu20. And that same version also fixed the windows compilation using the pip's frida-compile.

i'll look into that next week, it's not clear to me where the bug is yet.

can you confirm the same behaviour? (Only happens on windows)

**Comment by trufae** [comment] 2023-05-18 14:29
dupe of dupe of https://github.com/nowsecure/r2frida/issues/444 (there are 5 issues about r2frida not working on windows) when thats a known issue and probably a bug in frida, i'm slowly investigating the issue but i didnt managed to find the reason why the compiled scripts are not parsed properly by frida inside r2frida.

**Closed by trufae** 2023-05-18 14:29 UTC
